### ISSUE TITLE
10A model compitability

### ISSUE THREAD

**Issue by jayprojects** [hirschi-dev/renogy-rover-arduino#1]
Hi any idea if this library will work with Renogy 10 Amp model?
Also as you might know the Renogy controllers comes with RJ11/RJ12 port (not a standard 9pin com port). I haven't found any RS232 to TTL Converter that has RJ11/RJ12 port. what converter have you tested this with during your development?
Thanks for your time

**Comment by hirschi-dev** [comment]
Hi,
I do not own any 10 Amp model so I haven't tested them. According to this project: https://github.com/mickwheelz/NodeRenogy, they seem to use the same Modbus registers. As the controllers don't support  standard RJ11/RJ12 pinout, you'd have to build your own adapter (see link above). I used a Max3232 mini RS232 to TTL converter along with an RJ12 cable.
Let me know if it works!

**Comment by jayprojects** [comment]
hi,
Thanks for quick response!
so basically we need  RS232 to TTL Converter  plus com (RS232) to  RJ12 converter/cable. 
And as to 10A compatibility seems hopeful, need to try my luck!
Thanks again.

**Comment by hirschi-dev** [comment]
I didn't use a COM converter - just soldered the RJ12 connector to the RS232/TTL converter. Anyway, be sure to wire your pins correctly!
