### ISSUE TITLE
Some functions missing free() at the end

### ISSUE THREAD

**Issue by ray-mathers** [hirschi-dev/renogy-rover-arduino#3]
Hi. I've been using your renogy interface for a few days on my Arduino
I have a Renogy 20A MPPT and RS232-TTL convertor and Arduino Uno and NRF24L01 wireless.
I noticed that after a few hours of continuous polling, the Arduino was send out corrupted data over the wireless.
(from my programming background) I worked out it was the getBatteryState and getPanelState and getProductName are mssing the free(values) at the end of the functions. You are calling "new uint16_t[registerLength];" which Arduino does a malloc, but it is not being released.
I added free() at the end to the three functions as a test and it us running without problems for thousands of polling now.

I also think you need to add the free() if the readHoldingRegisters fails.
eg.
  if (!_readHoldingRegisters(registerBase, registerLength, values)) {
	**free(values);**
        return 0;
    } else

**Comment by hirschi-dev** [comment]
Hi, thank you. I added some delete statements to release the memory properly. (5bdab9f)
